version: '3.1'

networks:
  net:

services:
  db:
    image: postgres:alpine
    networks:
      net:
        aliases:
          - postgres
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - batebola_db_data:/var/lib/postgresql/data

  app:
    image: batebola
    build: .
    ports:
      - 3000:3000
    env_file:
      - .env
    depends_on:
      - db
    links:
      - db
    volumes:
      - .:/var/app
    networks:
      net:
        aliases:
          - app

  nginx:
    image: nginx
    command: ["nginx-debug", "-g", "daemon off;"]
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - app
    networks:
      net:
        aliases:
          - nginx

volumes:
  batebola_db_data:
